### ISSUE TITLE
[Request] Privileges

### ISSUE THREAD

**Issue by noraj** [aepereyra/lfimap#6]
Can you name me as a Collaborator `Settings > Collaborators > Add collaborator`, I'll work on the script and the project.

**Comment by aepereyra** [comment]
Sorry by the delay. I wasn't be notify and i don't use this account form  a long time ago.
Now you are a collaborator! Sorry by the delay. if you want to write me please send a mail to aepereyra (at) gmail (dot) com.

Regards

**Comment by noraj** [comment]
Sorry I have no more time for this project now.

**Comment by aepereyra** [comment]
That's ok

Thanks anyway
